name: Bug report
description: Something doesn't build, CI fails, or docs are wrong
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include logs / screenshots.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      value: |
        Steps:
        1.
        2.
        3.
    validations:
      required: true
